name: SonarQube Scan

on:
  push:
    branches:
      - main  # You can change this to your preferred branch
  workflow_dispatch:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=myusername_myrepository \
            -Dsonar.host.url=https://8532-59-145-123-10.ngrok-free.app \
            -Dsonar.login=squ_75103e00bdd50172378e56044918a082b018b803

