name: SonarQube with Dependency-Check

on:
  push:
    branches:
      - main
      - 'release/*'
      - 'feature/*'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'


      - name: Run OWASP Dependency-Check
        run: |
          mvn clean dependency-check:check

      - name: Install SonarQube Scanner
        run: npm install -g sonar-scanner
        
      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=myusername_myrepository \
            -Dsonar.host.url=https://8532-59-145-123-10.ngrok-free.app \
            -Dsonar.login=squ_75103e00bdd50172378e56044918a082b018b803 \
            -DskipTests
